from tkinter import *
from PIL import ImageTk,Image
import webbrowser
import pymysql
window =Tk()
window.geometry('400x600')
window.configure(background='white')
def signup():
    num=entry.get()
    name=entry2.get()
    email=entry3.get()
    password=entry4.get()
    dbc=pymysql.connect(host='localhost',user='root',passwd='',db='swiggy')
    c=dbc.cursor()
    try:
          sql = "INSERT INTO signup(phone number	Name	Email	Password	) VALUES (%s,%s,%s,%s)"
          val = (num,name,email,password)
          c.execute(sql,val)
          dbc.commit()
    except Exception as e:
        print(e)
        dbc.rollback()
        dbc.close()    
label1=Label(window,text='Sign up',bd=0,font=('arial',20,"bold"),bg='white')
label1.place(x=20,y=40)
label2=Label(window,text='or',font=('arial',10),bg='white',bd=0)
label2.place(x=20,y=72)
button1=Button(window,text='log in to your account',font=('arial',10),fg='red',bg='white',bd=0)
button1.place(x=35,y=70)
image1=ImageTk.PhotoImage(file='C:\\Users\\Lakshmi\\Desktop\\image\\img8.png')
label3=Label(window,image=image1,bd=0)
label3.place(x=250,y=4)
label4=Label(window,text='Phone number',font=('arial',9),fg='grey',bg='white',bd=0)
label4.place(x=30,y=150)
entry=Entry(window,width=45,font=('arial',10),fg='black' ,bg='white',highlightthickness=1,bd=0)
entry.place(x=30,y=170,height=40)
entry.config(highlightbackground = "grey", highlightcolor= "grey")
label5=Label(window,text='Name',font=('arial',9),fg='grey',bg='white',bd=0)
label5.place(x=30,y=215)
entry2=Entry(window,width=45,font=('arial',10),fg='black' ,bg='white',highlightthickness=1,bd=0)
entry2.place(x=30,y=240,height=40)
entry2.config(highlightbackground = "grey", highlightcolor= "grey")
label5=Label(window,text='Email',font=('arial',9),fg='grey',bg='white',bd=0)
label5.place(x=30,y=285)
entry3=Entry(window,width=45,font=('arial',10),fg='black' ,bg='white',highlightthickness=1,bd=0)
entry3.place(x=30,y=310,height=40)
entry3.config(highlightbackground = "grey", highlightcolor= "grey")
label6=Label(window,text='Password',font=('arial',9),fg='grey',bg='white',bd=0)
label6.place(x=30,y=350)
entry4=Entry(window,width=45,font=('arial',10),show='*',fg='black' ,bg='white',highlightthickness=1,bd=0)
entry4.place(x=30,y=380,height=40)
entry4.config(highlightbackground = "grey", highlightcolor= "grey")
label7=Label(window,text='Have a referal code?',font=('arial',12,'bold'),fg='blue',bg='white',bd=0)
label7.place(x=30,y=450)
button2=Button(window,width=40,text='CONTINUE',font=('callibri',10,'bold'),fg='white' ,bg='orange',command=signup)
button2.place(x=30,y=480,height=50)
window.mainloop()
